# vim: set ft=yaml ts=2 expandtab:
---

- name: converge selinux
  hosts: all,!infrastructure_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  roles:

  - role: mafalb.ansible.node
    ansible_node_features:
    - selinux
  - role: mafalb.selinux.selinux
  - role: mafalb.selinux.setroubleshootd
  - role: mafalb.selinux.setroubleshoot
    state: absent
  - role: mafalb.selinux.mcstrans
    state: absent

...
